# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e2df700e1e3e566bb715bb773d72b9c97232bed3f3f718a3ab409cf6066d2a2b0cbc04c472ee96c9add3f80e2b120c478abb2a9c28b247f733274da43d2777d0

test:
  secret_key_base: d4a47037d81b3517bc80a085b7e58bdd49ea0f6374e84b66e53bf525058cd5ff23e7302c3b09f9d0985b9ef28e06f0bc15ec037d4f902e85b9daeda054292ace

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
